name: System stat daemon

on:
  push:
  pull_request:
    types: [opened]

env:
  GO111MODULE: "on"

jobs:
  tests_by_makefile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Check out code
        uses: actions/checkout@v2

      - name: make lint
        run: make lint
        working-directory: .

      - name: make test
        run: make test
        working-directory: .

      - name: make build daemon
        run: make build_daemon
        working-directory: .

      - name: make build client
        run: make build_client
        working-directory: .
